// Girly Microservices - Gradle Settings
// Defines all projects in the multi-module build

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'girly'

// Include common libraries
include 'lib:girly-common'
include 'lib:girly-db'
include 'lib:girly-models'
include 'lib:girly-events'
include 'lib:girly-tooling'

// Include microservices
include 'services:user-service'
include 'services:ideas'

// Configure project directories
project(':lib:girly-common').projectDir = file('lib/girly-common')
project(':lib:girly-db').projectDir = file('lib/girly-db')
project(':lib:girly-models').projectDir = file('lib/girly-models')
project(':lib:girly-events').projectDir = file('lib/girly-events')
project(':lib:girly-tooling').projectDir = file('lib/girly-tooling')

project(':services:user-service').projectDir = file('services/user-service')
project(':services:ideas').projectDir = file('services/ideas')
